Feature/plcn 203 create nested contact person deal
it-minds/itm_pelican-crm-frontend pull request #45
Opened 2022-12-07 13:39 UTC by s-bogelund

2022-12-08 09:24 UTC, itm-mne commented on src/components/wall-of-clients/NestedContactPerson.tsx
>  	}, [contact]);
Same goes for remaining useEffects concerning mappingof data

2022-12-08 09:44 UTC, itm-mne commented on src/pages/WallOfClients.tsx
> +			{loading && <CompanyCardsSkeleton numSkeletons={10} />}
Should we have another Skeleton component for when we are loading paginated data? Maybe a component with fewer skeleton lines? If so, please create a JIRA task.

2022-12-08 09:46 UTC, itm-mne requested changes
Move mapping from useEffects into functions for NestedContactPerson.tsx

2022-12-09 08:27 UTC, AntonEsbjergIT-Minds reviewed
The nesting indicator is not visible in lightmode.
Reddit line cannot be seen in lightmode
And the dividing line in the summaries is very faint in lightmode

2022-12-09 08:32 UTC, merged