Feature/plcn 275 wall of clients infinity scroll
it-minds/itm_pelican-crm-frontend pull request #47
Opened 2022-12-09 08:49 UTC by itm-mne

2022-12-09 09:17 UTC, s-bogelund requested changes

2022-12-09 09:17 UTC, s-bogelund commented on src/pages/WallOfClients.tsx
>  import { useQuery } from '@apollo/client';
Maybe add small debounce timer

2022-12-09 12:05 UTC, vla-ITM requested changes
It looks great! This logic could be moved into a custom hook to make the component a lot more clean. Something along the lines of:

`const useInfinityScroll(callback)`
or
`const useScrollAction(callback)`

Where the infinity scroll callback would be one that happens every time scroll is over 90.
And the scroll action callback would be one that gives the percentage as a param to take action on.

Hope it makes sense. Otherwise let's have a talk.

I think the flag method used now is simple and good. Especially if moved into a custom hook. However, this could also be solved with a debounce timer. Which would be suitable for making a more generic version. If that is something you want, take a look at https://usehooks.com/useDebounce/ for their implementation. Then you can reuse that hook other places.

Cheerio! And nice work! 👍

2022-12-12 12:48 UTC, Nicolai-Bak commented on src/pages/WallOfClients.tsx
>  		}
Don't know if the number is just for testing but I would consider loading more than 5 clients at a time. 
When entering wall of clients, you only see 5 client and there is only a small 'Found x results" indicating that more data can be loaded

2022-12-13 10:04 UTC, merged