Feature/plcn 22 create checkbox group
it-minds/itm_pelican-crm-frontend pull request #52
Opened 2022-12-15 10:58 UTC by s-bogelund

Generic CheckboxGroup, that is to be used in multiple different filters. Please ignore the commented out LocationFilter :)

2022-12-15 12:40 UTC, Nicolai-Bak commented on src/assets/icons/DialogIcon.tsx
> +export default DialogIcon;
Should this be added? It is not used

2022-12-16 08:13 UTC, AntonEsbjergIT-Minds requested changes

2022-12-16 08:19 UTC, AntonEsbjergIT-Minds reviewed
Super lækker animation når man trykker på en checkbox btw.

2022-12-16 08:34 UTC, itm-mne commented on src/pages/WallOfClients.tsx
> +	]);
Don't we have the data to generate these lists dynamically, based on the clients, deals, etc. in the application? Or is this not a part of the task?

2022-12-16 14:12 UTC, AntonEsbjergIT-Minds approved these changes

2022-12-20 09:10 UTC, s-bogelund commented on src/components/common/CheckboxGroup.tsx
> +import {
No that's a finished filter component

2022-12-20 09:12 UTC, s-bogelund commented on src/pages/WallOfClients.tsx
> +	]);
We probably do, but the task is just about creating a generic component and not its specific use case. This is why I just used dummy data :)
I will delete it, however, cause we don't need it in dev/main

2022-12-20 09:40 UTC, s-bogelund commented on src/components/common/CheckboxGroup.tsx
> +		return checkboxes.map((checkbox, index) => {
Fixed

2022-12-20 12:09 UTC, vla-ITM reviewed
Looks good! I have some comments mostly on the structure of some of the files. Otherwise good work! 👍

2022-12-20 12:09 UTC, vla-ITM commented on src/assets/icons/DialogIcon.tsx
> +export default DialogIcon;
Like Nicolai pointed out, I don't see where this is used.

And also. Would it be possible to import the svg instead. Something like this:

`import DialogSvg from "./dialog.svg" `

And then setting it up something like this: 

`<SvgIcon component={DialogSvg} viewBox="0 0 64 64" />`

You can set the SVG import up in Vite according to this post - look at 6. https://www.freecodecamp.org/news/how-to-import-svgs-in-react-and-vite/

And also I think that I would probably put this in /components instea, rather than /assets.

2022-12-20 12:09 UTC, vla-ITM commented on src/assets/icons/dialog.svg
> +			/>
This does not seem to be used. Refer to my previous comment and then perhaps comment this back in. That way we can get a preview of the file, which will help when developing.

2022-12-20 12:09 UTC, vla-ITM commented on src/components/common/filters/LocationFilter.tsx
> +		// </Box>
Is there a reason that this has been commented out? It could potentially be misleading to other developers to have an empty component like this.

2022-12-20 12:09 UTC, vla-ITM commented on src/pages/WallOfClients.tsx
> +				<SecondaryFilterContainer></SecondaryFilterContainer>
This component does not make sense without children. Consider removing it.

2022-12-28 10:49 UTC, merged