Feature/plcn 401 create login page
it-minds/itm_pelican-crm-frontend pull request #59
Opened 2023-01-05 13:04 UTC by s-bogelund

Implemented LoginPage and LoginForm. Still needs to make call to backend after login attempt, but this is not yet implemented. As of now, it will show Toast saying that login failed every time form is submitted.

2023-01-06 07:42 UTC, AntonEsbjergIT-Minds requested changes

2023-01-06 07:42 UTC, AntonEsbjergIT-Minds commented on src/components/login/LoginForm.tsx
> +	// 	// Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, and one number
We changed the password requirements on the backend so that it is a minimum of 8 characters and also needs one special character

2023-01-06 07:42 UTC, AntonEsbjergIT-Minds commented on src/components/login/LoginForm.tsx
> +						<Typography variant="body2" color="primary">
The color of the text needs to be changed. 
![image](https://user-images.githubusercontent.com/112855152/210953456-ce5bf580-52c4-4323-a08c-f36ef0ece39f.png)

2023-01-06 07:42 UTC, AntonEsbjergIT-Minds commented on src/components/login/LoginForm.tsx
> +						<Typography variant="body2" color="primary">
![image](https://user-images.githubusercontent.com/112855152/210953648-25d315c8-e195-42f7-a80d-146353566361.png)

2023-01-09 08:33 UTC, s-bogelund commented on src/components/login/LoginForm.tsx
> +						<Typography variant="body2" color="primary">
Fixed :+1:

2023-01-09 09:32 UTC, itm-mne approved these changes

2023-01-09 09:57 UTC, AntonEsbjergIT-Minds approved these changes

2023-01-09 12:17 UTC, merged