Feature/plcn 400 setup protected routes
it-minds/itm_pelican-crm-frontend pull request #60
Opened 2023-01-05 13:18 UTC by s-bogelund

Used tools available with Apollo to handle user state, namely useReactiveVar and makeVar. All the logic is stored in the UserStore file.

Some of the functionality should maybe be split into a few more files, especially if we need to add additional logic.

2023-01-06 07:48 UTC, AntonEsbjergIT-Minds commented on src/components/login/LoginForm.tsx
> +import {
Should this PR not be a draft until 401 is merged? seems like you have duplicated code.

2023-01-06 09:18 UTC, s-bogelund commented on src/components/login/LoginForm.tsx
> +import {
True dat. Has been changed :)

2023-01-09 13:50 UTC, itm-mne commented on src/Content.tsx
> +	console.log('currentUser', currentUser);
Remove clog

2023-01-09 13:50 UTC, itm-mne commented on src/Content.tsx
> +											Here you should hopefully be able to create a new user :)
Maybe add TODO here to show what you wanna do with it.

2023-01-09 14:02 UTC, itm-mne requested changes
Minor cleanup and suggestions for use of Access-wrapper on login-page. Also make sure to resolve conflicts with `dev`.

2023-01-09 14:18 UTC, s-bogelund commented on src/Content.tsx
> +											Here you should hopefully be able to create a new user :)
Added in other branch

2023-01-09 14:22 UTC, s-bogelund commented on src/pages/Login.tsx
> +		</Access>
Will create seperate issue

2023-01-09 14:34 UTC, merged