Feature/plcn 404 create admin form
it-minds/itm_pelican-crm-frontend pull request #63
Opened 2023-01-12 12:56 UTC by s-bogelund

This includes both plcn 403 and 404.
An admin page has been implemented including routes and links in navbar.
The CreateUserForm uses the same logic as the backend to ensure password rules are being followed as well as ensuring the admin has typed the same password twice. If not, the user will get an appropriate error in an Alert.

2023-01-12 13:57 UTC, itm-mne commented on src/components/admin/CreateUserForm.tsx
> +	const [invalidPassword, setInvalidPassword] = useState(false);
Could be prefixed with "is" to signify that it is a boolean and not the invalid password.

2023-01-12 14:03 UTC, itm-mne requested changes
Small rename - else looks fine

2023-01-13 08:50 UTC, AntonEsbjergIT-Minds approved these changes

2023-01-13 10:37 UTC, itm-mne approved these changes

2023-01-16 09:25 UTC, EsBjerrum commented on src/components/login/LoginForm.tsx
> +	//TODO: Move this logic to a create user page instead of login page
Det er vel flyttet, så skal det ikke bare slettes i stedet for udkommenteres?

2023-01-16 09:32 UTC, EsBjerrum approved these changes

2023-01-16 09:32 UTC, EsBjerrum commented on src/pages/Login.tsx
> +				sx={{ width: '600px' }}
Måske lav en snackbarcomponent, der havde den rigtige styling og positionering, som kunne genbruges :)

2023-01-16 14:11 UTC, merged